"""added a column for author names

Revision ID: 45382dcc3015
Revises: cbf8c9921d3b
Create Date: 2021-01-16 18:40:03.191496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45382dcc3015'
down_revision = 'cbf8c9921d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'author')
    # ### end Alembic commands ###
